backend:
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
catalog:
  providers:
    github:
      catalogInfo:
        filters:
          branch: main
          repository: ".*"
      templates:
        filters:
          branch: main
          repository: ".*"
